spring.application.name=bry-facial-biometry-api
spring.datasource.url=jdbc:postgresql://localhost:5432/bry_facial_biometry
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

biometry.similarity-threshold=0.85
